
version: '3'
services:
  postgres_db:
    image: postgres:11.1
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: animaldb
      POSTGRES_USER: myuser
    ports:
      - 5433:5432
    networks:
      - app-tier
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d

  python_app:
    build:
      context: .
      dockerfile: compose/Dockerfile
    depends_on:
      - postgres_db
    networks:
      - app-tier
    volumes:
      - ./src:/project/src
    command:
      tail -f /dev/null

networks:
  app-tier:
    driver: bridge